// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqli

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (*User, error)
}

var _ Querier = (*Queries)(nil)
